### ISSUE TITLE
Should we add other structural information to stream or trace properties?

### ISSUE THREAD

**Issue by SCEDC** [SCEDC/ground-motion-packet#7]
Should we include some properties that can also be found in V0 records?

1. floor?
2. channel number?

**Comment by steidljh** [comment]
It would be nice, but I'm not sure we want to add any additional information in the GM packet. This information won't always be available, and when it is, it's likely not going to be in a consistent place. I think since the SNCL should be unique it's ok to leave it to the user to investigate the structural schematic (assuming it exists) or waveform data file header to find this information.

**Comment by SCEDC** [comment]
group decided to add optional properties "stream_location" to housing property of stream
